### ISSUE TITLE
[Bug]: `enable_completions_update` and `enable_module_update` settings is reset after updating module

### ISSUE THREAD

**Issue by soredake** [abgox/PSCompletions#56]
### Before Start

- [X] You are using the latest version of PSCompletions.
- [X] You have read this repository's README file.
- [X] You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
- [X] You have visit https://pscompletions.pages.dev/

### What Powershell version are you using?

PowerShell

### What system are you using?

Windows

### Steps to reproduce

1) update module by doing:
```
function Remove-OldModules {
  $Latest = Get-InstalledModule
  foreach ($module in $Latest) {
    Write-Verbose -Message "Uninstalling old versions of $($module.Name) [latest is $( $module.Version)]" -Verbose
    Get-InstalledModule -Name $module.Name -AllVersions | Where-Object { $_.Version -ne $module.Version } | Uninstall-Module -Verbose 
  }
}

Get-InstalledModule | Update-Module

Remove-OldModules
```

### What is expected?

Settings should not be reset after module update

### What is actually happening?

Settings are reset after module update

**Comment by abgox** [comment]
- This is a bug in `5.1.1`, fixed in `5.1.2`.

**Comment by soredake** [comment]
Unfortunately, this is not fixed, after updating versions these settings is still reset.

**Comment by abgox** [comment]
This is rather bad news, as there is a logic bug that could cause the configuration items to all reset to the defaults.

**Comment by soredake** [comment]
Unfortunately, this problem is again bothering me.

**Comment by abgox** [comment]
I can't reproduce the issue, on my computer it won't reset.
